### ISSUE TITLE
Make new NFD tags

### ISSUE THREAD

**Issue by arneme** [arne-munch-ellingsen/AIOD-hw-agent#3]
As a start I will experiment with the mechanisms that allows the addition of custom labels. Next step will be to add labels for some of the "missing" hw agent metadata parts (i.e. metadata entries that can not be retrived from the default NFD labels).

**Comment by arne-munch-ellingsen** [comment]
Python code examples added in the nfd directory. The get_nfd_labels.py code gets the nfd labels and prints them in json format. The create_nfd_label.py creates a new label.

**Comment by arne-munch-ellingsen** [comment]
Created a Kubernetes app that sets a node feature discovery label (from within the Kubernetes cluster). The code is found in [nfd/kubernetes](https://github.com/arne-munch-ellingsen/AIOD-hw-agent/tree/main/nfd/kubernetes).
